# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Robotic_Artist_GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import Resources_rc

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.setWindowModality(QtCore.Qt.NonModal)
        mainWindow.setEnabled(True)
        mainWindow.resize(950, 600)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setMinimumSize(QtCore.QSize(950, 600))
        mainWindow.setMaximumSize(QtCore.QSize(950, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(159, 158, 158))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        mainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/MMP-Robotic-Artist/Code/Images/Icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setWindowOpacity(1.0)
        mainWindow.setDockNestingEnabled(False)
        mainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.MainView = QtGui.QWidget(mainWindow)
        self.MainView.setAutoFillBackground(False)
        self.MainView.setStyleSheet(_fromUtf8("background-color: rgb(199, 199, 231);"))
        self.MainView.setObjectName(_fromUtf8("MainView"))
        self.layoutWidget = QtGui.QWidget(self.MainView)
        self.layoutWidget.setGeometry(QtCore.QRect(-10, 0, 956, 602))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.base_layer = QtGui.QHBoxLayout(self.layoutWidget)
        self.base_layer.setObjectName(_fromUtf8("base_layer"))
        self.description_layer = QtGui.QVBoxLayout()
        self.description_layer.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.description_layer.setContentsMargins(20, 5, 0, -1)
        self.description_layer.setObjectName(_fromUtf8("description_layer"))
        self.Title = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Tlwg Typewriter"))
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setMouseTracking(True)
        self.Title.setStyleSheet(_fromUtf8("background-color: rgb(247, 23, 23);\n"
"border-right-color: rgb(247, 23, 23);\n"
"border-top-color: rgb(247, 23, 23);\n"
"border-bottom-color: rgb(30, 27, 24);\n"
""))
        self.Title.setFrameShape(QtGui.QFrame.Box)
        self.Title.setLineWidth(3)
        self.Title.setObjectName(_fromUtf8("Title"))
        self.description_layer.addWidget(self.Title)
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.description_layer.addItem(spacerItem)
        self.sub_title = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sub_title.sizePolicy().hasHeightForWidth())
        self.sub_title.setSizePolicy(sizePolicy)
        self.sub_title.setMinimumSize(QtCore.QSize(400, 0))
        self.sub_title.setObjectName(_fromUtf8("sub_title"))
        self.description_layer.addWidget(self.sub_title)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.description_layer.addItem(spacerItem1)
        self.description_text = QtGui.QTextBrowser(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_text.sizePolicy().hasHeightForWidth())
        self.description_text.setSizePolicy(sizePolicy)
        self.description_text.setMinimumSize(QtCore.QSize(400, 0))
        self.description_text.setFrameShape(QtGui.QFrame.NoFrame)
        self.description_text.setObjectName(_fromUtf8("description_text"))
        self.description_layer.addWidget(self.description_text)
        self.base_layer.addLayout(self.description_layer)
        self.line_separator = QtGui.QFrame(self.layoutWidget)
        self.line_separator.setWindowModality(QtCore.Qt.NonModal)
        self.line_separator.setFrameShadow(QtGui.QFrame.Plain)
        self.line_separator.setLineWidth(3)
        self.line_separator.setFrameShape(QtGui.QFrame.VLine)
        self.line_separator.setObjectName(_fromUtf8("line_separator"))
        self.base_layer.addWidget(self.line_separator)
        self.page_layer = QtGui.QStackedWidget(self.layoutWidget)
        self.page_layer.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_layer.sizePolicy().hasHeightForWidth())
        self.page_layer.setSizePolicy(sizePolicy)
        self.page_layer.setMinimumSize(QtCore.QSize(500, 600))
        self.page_layer.setObjectName(_fromUtf8("page_layer"))
        self.Video_Capture = QtGui.QWidget()
        self.Video_Capture.setObjectName(_fromUtf8("Video_Capture"))
        self.layoutWidget1 = QtGui.QWidget(self.Video_Capture)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 20, 491, 511))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.display_layer1 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.display_layer1.setObjectName(_fromUtf8("display_layer1"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.display_layer1.addItem(spacerItem2)
        self.video_capture = QtGui.QLabel(self.layoutWidget1)
        self.video_capture.setMinimumSize(QtCore.QSize(300, 300))
        self.video_capture.setObjectName(_fromUtf8("video_capture"))
        self.display_layer1.addWidget(self.video_capture)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.display_layer1.addItem(spacerItem3)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.check_process = QtGui.QCheckBox(self.layoutWidget1)
        self.check_process.setObjectName(_fromUtf8("check_process"))
        self.gridLayout.addWidget(self.check_process, 0, 0, 1, 1)
        self.check_use_after = QtGui.QCheckBox(self.layoutWidget1)
        self.check_use_after.setObjectName(_fromUtf8("check_use_after"))
        self.gridLayout.addWidget(self.check_use_after, 1, 0, 1, 1)
        self.capture_picture = QtGui.QPushButton(self.layoutWidget1)
        self.capture_picture.setObjectName(_fromUtf8("capture_picture"))
        self.gridLayout.addWidget(self.capture_picture, 2, 0, 1, 1)
        self.display_layer1.addLayout(self.gridLayout)
        self.page_layer.addWidget(self.Video_Capture)
        self.picture_display = QtGui.QWidget()
        self.picture_display.setObjectName(_fromUtf8("picture_display"))
        self.layoutWidget2 = QtGui.QWidget(self.picture_display)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 20, 491, 511))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.display_layer2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.display_layer2.setObjectName(_fromUtf8("display_layer2"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.display_layer2.addItem(spacerItem4)
        self.captured_image = QtGui.QLabel(self.layoutWidget2)
        self.captured_image.setMinimumSize(QtCore.QSize(300, 300))
        self.captured_image.setObjectName(_fromUtf8("captured_image"))
        self.display_layer2.addWidget(self.captured_image)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.display_layer2.addItem(spacerItem5)
        self.question_field = QtGui.QVBoxLayout()
        self.question_field.setObjectName(_fromUtf8("question_field"))
        self.question1 = QtGui.QLabel(self.layoutWidget2)
        self.question1.setObjectName(_fromUtf8("question1"))
        self.question_field.addWidget(self.question1)
        self.yes_no_field = QtGui.QHBoxLayout()
        self.yes_no_field.setObjectName(_fromUtf8("yes_no_field"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.yes_no_field.addItem(spacerItem6)
        self.yes_no_button = QtGui.QDialogButtonBox(self.layoutWidget2)
        self.yes_no_button.setStandardButtons(QtGui.QDialogButtonBox.No|QtGui.QDialogButtonBox.Yes)
        self.yes_no_button.setObjectName(_fromUtf8("yes_no_button"))
        self.yes_no_field.addWidget(self.yes_no_button)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.yes_no_field.addItem(spacerItem7)
        self.question_field.addLayout(self.yes_no_field)
        self.display_layer2.addLayout(self.question_field)
        self.page_layer.addWidget(self.picture_display)
        self.Style_Selection = QtGui.QWidget()
        self.Style_Selection.setObjectName(_fromUtf8("Style_Selection"))
        self.btn_continue1 = QtGui.QPushButton(self.Style_Selection)
        self.btn_continue1.setGeometry(QtCore.QRect(200, 430, 99, 27))
        self.btn_continue1.setObjectName(_fromUtf8("btn_continue1"))
        self.layoutWidget3 = QtGui.QWidget(self.Style_Selection)
        self.layoutWidget3.setGeometry(QtCore.QRect(40, 40, 422, 318))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.displayer_layer3 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.displayer_layer3.setObjectName(_fromUtf8("displayer_layer3"))
        self.label_select_statement = QtGui.QLabel(self.layoutWidget3)
        self.label_select_statement.setObjectName(_fromUtf8("label_select_statement"))
        self.displayer_layer3.addWidget(self.label_select_statement)
        self.Image_selection_layer = QtGui.QGridLayout()
        self.Image_selection_layer.setObjectName(_fromUtf8("Image_selection_layer"))
        self.image_your_picture = QtGui.QLabel(self.layoutWidget3)
        self.image_your_picture.setMinimumSize(QtCore.QSize(100, 100))
        self.image_your_picture.setFrameShape(QtGui.QFrame.StyledPanel)
        self.image_your_picture.setFrameShadow(QtGui.QFrame.Raised)
        self.image_your_picture.setLineWidth(5)
        self.image_your_picture.setObjectName(_fromUtf8("image_your_picture"))
        self.Image_selection_layer.addWidget(self.image_your_picture, 0, 0, 1, 1)
        self.image_style1 = QtGui.QLabel(self.layoutWidget3)
        self.image_style1.setMinimumSize(QtCore.QSize(100, 100))
        self.image_style1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.image_style1.setFrameShadow(QtGui.QFrame.Raised)
        self.image_style1.setLineWidth(5)
        self.image_style1.setObjectName(_fromUtf8("image_style1"))
        self.Image_selection_layer.addWidget(self.image_style1, 0, 1, 1, 1)
        self.image_style2 = QtGui.QLabel(self.layoutWidget3)
        self.image_style2.setMinimumSize(QtCore.QSize(100, 100))
        self.image_style2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.image_style2.setFrameShadow(QtGui.QFrame.Raised)
        self.image_style2.setLineWidth(5)
        self.image_style2.setObjectName(_fromUtf8("image_style2"))
        self.Image_selection_layer.addWidget(self.image_style2, 0, 2, 1, 1)
        self.image_style3 = QtGui.QLabel(self.layoutWidget3)
        self.image_style3.setMinimumSize(QtCore.QSize(100, 100))
        self.image_style3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.image_style3.setFrameShadow(QtGui.QFrame.Raised)
        self.image_style3.setLineWidth(5)
        self.image_style3.setObjectName(_fromUtf8("image_style3"))
        self.Image_selection_layer.addWidget(self.image_style3, 0, 3, 1, 1)
        self.label_your_picture = QtGui.QLabel(self.layoutWidget3)
        self.label_your_picture.setObjectName(_fromUtf8("label_your_picture"))
        self.Image_selection_layer.addWidget(self.label_your_picture, 1, 0, 1, 1)
        self.check_style1 = QtGui.QCheckBox(self.layoutWidget3)
        self.check_style1.setObjectName(_fromUtf8("check_style1"))
        self.Image_selection_layer.addWidget(self.check_style1, 1, 1, 1, 1)
        self.check_style2 = QtGui.QCheckBox(self.layoutWidget3)
        self.check_style2.setObjectName(_fromUtf8("check_style2"))
        self.Image_selection_layer.addWidget(self.check_style2, 1, 2, 1, 1)
        self.check_style3 = QtGui.QCheckBox(self.layoutWidget3)
        self.check_style3.setObjectName(_fromUtf8("check_style3"))
        self.Image_selection_layer.addWidget(self.check_style3, 1, 3, 1, 1)
        self.image_style4 = QtGui.QLabel(self.layoutWidget3)
        self.image_style4.setMinimumSize(QtCore.QSize(100, 100))
        self.image_style4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.image_style4.setFrameShadow(QtGui.QFrame.Raised)
        self.image_style4.setLineWidth(5)
        self.image_style4.setObjectName(_fromUtf8("image_style4"))
        self.Image_selection_layer.addWidget(self.image_style4, 2, 0, 1, 1)
        self.image_style5 = QtGui.QLabel(self.layoutWidget3)
        self.image_style5.setMinimumSize(QtCore.QSize(100, 100))
        self.image_style5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.image_style5.setFrameShadow(QtGui.QFrame.Raised)
        self.image_style5.setLineWidth(5)
        self.image_style5.setObjectName(_fromUtf8("image_style5"))
        self.Image_selection_layer.addWidget(self.image_style5, 2, 1, 1, 1)
        self.check_style4 = QtGui.QCheckBox(self.layoutWidget3)
        self.check_style4.setObjectName(_fromUtf8("check_style4"))
        self.Image_selection_layer.addWidget(self.check_style4, 3, 0, 1, 1)
        self.check_style5 = QtGui.QCheckBox(self.layoutWidget3)
        self.check_style5.setObjectName(_fromUtf8("check_style5"))
        self.Image_selection_layer.addWidget(self.check_style5, 3, 1, 1, 1)
        self.displayer_layer3.addLayout(self.Image_selection_layer)
        self.page_layer.addWidget(self.Style_Selection)
        self.Print_Confirmation = QtGui.QWidget()
        self.Print_Confirmation.setObjectName(_fromUtf8("Print_Confirmation"))
        self.layoutWidget_2 = QtGui.QWidget(self.Print_Confirmation)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 20, 491, 511))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.display_layer4 = QtGui.QVBoxLayout(self.layoutWidget_2)
        self.display_layer4.setObjectName(_fromUtf8("display_layer4"))
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.display_layer4.addItem(spacerItem8)
        self.styled_image = QtGui.QLabel(self.layoutWidget_2)
        self.styled_image.setMinimumSize(QtCore.QSize(300, 300))
        self.styled_image.setObjectName(_fromUtf8("styled_image"))
        self.display_layer4.addWidget(self.styled_image)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.display_layer4.addItem(spacerItem9)
        self.question_field2 = QtGui.QVBoxLayout()
        self.question_field2.setObjectName(_fromUtf8("question_field2"))
        self.label_question2 = QtGui.QLabel(self.layoutWidget_2)
        self.label_question2.setObjectName(_fromUtf8("label_question2"))
        self.question_field2.addWidget(self.label_question2)
        self.yes_no_field2 = QtGui.QHBoxLayout()
        self.yes_no_field2.setObjectName(_fromUtf8("yes_no_field2"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.yes_no_field2.addItem(spacerItem10)
        self.yes_no_button2 = QtGui.QDialogButtonBox(self.layoutWidget_2)
        self.yes_no_button2.setStandardButtons(QtGui.QDialogButtonBox.No|QtGui.QDialogButtonBox.Yes)
        self.yes_no_button2.setObjectName(_fromUtf8("yes_no_button2"))
        self.yes_no_field2.addWidget(self.yes_no_button2)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.yes_no_field2.addItem(spacerItem11)
        self.question_field2.addLayout(self.yes_no_field2)
        self.display_layer4.addLayout(self.question_field2)
        self.page_layer.addWidget(self.Print_Confirmation)
        self.base_layer.addWidget(self.page_layer)
        mainWindow.setCentralWidget(self.MainView)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuAdmin = QtGui.QMenu(self.menubar)
        self.menuAdmin.setObjectName(_fromUtf8("menuAdmin"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(mainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit_Application = QtGui.QAction(mainWindow)
        self.actionExit_Application.setObjectName(_fromUtf8("actionExit_Application"))
        self.actionLogin = QtGui.QAction(mainWindow)
        self.actionLogin.setObjectName(_fromUtf8("actionLogin"))
        self.actionToggle_Admin_View = QtGui.QAction(mainWindow)
        self.actionToggle_Admin_View.setObjectName(_fromUtf8("actionToggle_Admin_View"))
        self.actionTutorial = QtGui.QAction(mainWindow)
        self.actionTutorial.setObjectName(_fromUtf8("actionTutorial"))
        self.menuHelp.addAction(self.actionTutorial)
        self.menuAdmin.addAction(self.actionLogin)
        self.menuAdmin.addSeparator()
        self.menuAdmin.addAction(self.actionToggle_Admin_View)
        self.menuFile.addAction(self.actionExit_Application)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAdmin.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.page_layer.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Robotic Artist : Walter", None))
        self.Title.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Robotic Artist : Walter</p></body></html>", None))
        self.sub_title.setText(_translate("mainWindow", "Description:", None))
        self.description_text.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">this is where my project description will go. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.video_capture.setText(_translate("mainWindow", "This is where the video feed will go", None))
        self.check_process.setText(_translate("mainWindow", "Tick to allow photos to be processed in this app", None))
        self.check_use_after.setText(_translate("mainWindow", "Allow images to be used for testing or presentation purposes", None))
        self.capture_picture.setText(_translate("mainWindow", "Capture Picture", None))
        self.captured_image.setText(_translate("mainWindow", "This is where the picture that was taken will be displayed", None))
        self.question1.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Is this the picture  you would like to use?</p></body></html>", None))
        self.btn_continue1.setText(_translate("mainWindow", "Continue", None))
        self.label_select_statement.setText(_translate("mainWindow", "<html><head/><body><p>Please select style: </p><p>(select image for the one you want)</p></body></html>", None))
        self.image_your_picture.setText(_translate("mainWindow", "<html><head/><body><p><br/></p><p>Image</p></body></html>", None))
        self.image_style1.setText(_translate("mainWindow", "<html><head/><body><p><br/></p><p>Image</p></body></html>", None))
        self.image_style2.setText(_translate("mainWindow", "<html><head/><body><p><br/></p><p>Image</p></body></html>", None))
        self.image_style3.setText(_translate("mainWindow", "<html><head/><body><p><br/></p><p>Image</p></body></html>", None))
        self.label_your_picture.setText(_translate("mainWindow", "Your Picture", None))
        self.check_style1.setText(_translate("mainWindow", "Style 1", None))
        self.check_style2.setText(_translate("mainWindow", "Style 2", None))
        self.check_style3.setText(_translate("mainWindow", "Style 3", None))
        self.image_style4.setText(_translate("mainWindow", "<html><head/><body><p><br/></p><p>Image</p></body></html>", None))
        self.image_style5.setText(_translate("mainWindow", "<html><head/><body><p><br/></p><p>Image</p></body></html>", None))
        self.check_style4.setText(_translate("mainWindow", "Style 4", None))
        self.check_style5.setText(_translate("mainWindow", "Style 5", None))
        self.styled_image.setText(_translate("mainWindow", "This is where the picture that was processed will be displayed", None))
        self.label_question2.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\">Is this the style that you would like?</p></body></html>", None))
        self.menuHelp.setTitle(_translate("mainWindow", "Help", None))
        self.menuAdmin.setTitle(_translate("mainWindow", "Admin", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("mainWindow", "toolBar", None))
        self.actionExit_Application.setText(_translate("mainWindow", "Exit Application", None))
        self.actionLogin.setText(_translate("mainWindow", "Login", None))
        self.actionToggle_Admin_View.setText(_translate("mainWindow", "Toggle Admin View", None))
        self.actionTutorial.setText(_translate("mainWindow", "Tutorial", None))
